release-schema.json: add hasNonDisclosureAgreement, nonDisclosureAgre…
open-contracting-extensions/ocds_contractTerms_extension pull request #5
Opened 2023-04-12 08:44 UTC by odscjen

…ement, CustomerService, and contractTerms.customerServices

2023-04-13 03:43 UTC, duncandewhurst requested changes

2023-04-13 03:43 UTC, duncandewhurst commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-711 (Contract Terms), BT-801 (Non Disclosure Agreement), BT-802 (Non Disclosure Agreement Description), OPT-071 (Quality Target
As in the other PRs, I think that we should preserve the reference to OCDS for the European Union.

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "title": "Has non disclosure agreement",
```suggestion
          "title": "Has non-disclosure agreement",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "Whether or not the contract execution will require the use of a non disclosure agreement.",
```suggestion
          "description": "Whether contract execution requires a non-disclosure agreement.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "title": "Non disclosure agreement",
```suggestion
          "title": "Non-disclosure agreement",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The nature and extent of the non disclosure agreement required as part of the contract execution.",
```suggestion
          "description": "The nature and extent of the non-disclosure agreement required as part of the contract execution.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The nature and extent of the non disclosure agreement required as part of the contract execution.",
Is the 'nature and extent' wording taken from somewhere? I wonder if we should have a more generic description in line with the title and description of BT-802, e.g. "A description of the non-disclosure agreement required for contract execution".

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The customer services the supplier is required to supply as part of this contract.",
```suggestion
          "description": "Information about customer service requirements.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +      "description": "Information about a customer service requirement linked to this contract.",
```suggestion
      "description": "A customer service requirement.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The code that defines the type of customer service requirement.",
```suggestion
          "description": "The type of this customer service requirement.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The name of the customer service requirement.",
```suggestion
          "description": "A name for this customer service requirement.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The description of the customer service requirement.",
```suggestion
          "description": "A description of this customer service requirement.",
```

2023-04-13 03:43 UTC, duncandewhurst commented on README.md
> +* Add `hasNonDisclosureAgreement`, `nonDisclosureAgreement`, `CustomerService` and `contractTerms.customerServices`.
```suggestion
* Add `.hasNonDisclosureAgreement`, `.nonDisclosureAgreement` and `.customerServices` fields.
```

2023-04-13 03:43 UTC, duncandewhurst commented on README.md
> +      "nonDisclosureAgreement": "A Non Disclosure Agreement will need to ...",
```suggestion
      "nonDisclosureAgreement": "A non-disclosure agreement is required in order to...",
```

2023-04-13 03:43 UTC, duncandewhurst commented on README.md
> +          "nonDisclosureAgreement": "A Non Disclosure Agreement will need to ...",
```suggestion
          "nonDisclosureAgreement": "A non-disclosure agreement is required in order to...",
```

2023-04-25 15:44 UTC, odscjen commented on release-schema.json
> +          "description": "The nature and extent of the non disclosure agreement required as part of the contract execution.",
It likely did come from somewhere but I can't find or remember where right now so I think you're rephrasing is better, I'll update that :)

2023-04-25 15:46 UTC, odscjen commented on README.md
> +      "nonDisclosureAgreement": "A Non Disclosure Agreement will need to ...",
This one I had lifted directly from the eForms example but happy to go with your suggestion

2023-04-25 15:56 UTC, odscjen commented on README.md
> +* Add `hasNonDisclosureAgreement`, `nonDisclosureAgreement`, `CustomerService` and `contractTerms.customerServices`.
I did commit this but then the periods made the tests fail so I removed them again

2023-04-27 05:21 UTC, duncandewhurst commented on README.md
> +* Add `hasNonDisclosureAgreement`, `nonDisclosureAgreement`, `CustomerService` and `contractTerms.customerServices`.
Ah, sorry!

2023-04-27 05:23 UTC, duncandewhurst approved these changes

2023-04-27 16:09 UTC, jpmckinney approved these changes

2023-04-27 16:10 UTC, merged